/**
 * AI Evidence Investigator — the independent mission for Course 1, Lesson 3.
 *
 * The point of this activity is a habit of speech: *"It might be AI-generated
 * because…"* rather than *"AI definitely made this."* So the scoring is
 * deliberately shaped against overconfidence — a "definitely" answer is never
 * accepted from appearance alone, however good the observations are.
 *
 * Two of the six items really are human-made and two are genuinely unknowable.
 * If every item were AI, a child would learn to answer "AI" every time and
 * still score well, which teaches the opposite of the lesson.
 */

export type ConclusionId = 'definitely-ai' | 'might-ai' | 'definitely-human' | 'not-enough';

export const CONCLUSIONS: Array<{ id: ConclusionId; label: string; emoji: string }> = [
  { id: 'definitely-ai', label: 'It was definitely made by AI', emoji: '🤖' },
  { id: 'might-ai', label: 'It might be AI-generated', emoji: '🤔' },
  { id: 'definitely-human', label: 'It was definitely made by a person', emoji: '🧑‍🎨' },
  { id: 'not-enough', label: 'There is not enough evidence to decide', emoji: '🔎' },
];

export interface ObservationCard {
  id: string;
  label: string;
  emoji: string;
}

export const OBSERVATIONS: ObservationCard[] = [
  { id: 'perfect', label: 'Details look unusually perfect', emoji: '✨' },
  { id: 'distorted', label: 'Some parts look distorted', emoji: '🌀' },
  { id: 'letters', label: 'Text or letters look strange', emoji: '🔤' },
  { id: 'lighting', label: 'Lighting or shadows do not match', emoji: '💡' },
  { id: 'style', label: 'The style changes in different areas', emoji: '🎨' },
  { id: 'repeats', label: 'The content repeats itself', emoji: '🔁' },
  { id: 'voice', label: 'The voice sounds unnatural', emoji: '🗣️' },
  { id: 'handmade', label: 'The content looks handmade', emoji: '✏️' },
  { id: 'edited', label: 'The content looks digitally edited', emoji: '🖥️' },
  { id: 'none', label: 'I do not see enough evidence', emoji: '🤷' },
];

/** The stronger evidence a real investigation would gather. */
export const SOURCE_CHECKS: Array<{ id: string; label: string; emoji: string; good: boolean }> = [
  { id: 'creator', label: 'Ask the creator', emoji: '🙋', good: true },
  { id: 'file', label: 'Check the original file information', emoji: '📁', good: true },
  { id: 'history', label: 'Review the creation history', emoji: '🕰️', good: true },
  { id: 'label', label: 'Look for an AI disclosure label', emoji: '🏷️', good: true },
  { id: 'website', label: 'Check the source website', emoji: '🌐', good: true },
  { id: 'impression', label: 'Use only my first impression', emoji: '👀', good: false },
];

export type ItemKind = 'image' | 'text' | 'audio';

export interface EvidenceItem {
  id: string;
  kind: ItemKind;
  title: string;
  /** Emoji stand-in for the artwork, or the text of the passage. */
  display: string;
  /** Describes what is visible, for anyone using a screen reader. */
  label: string;
  /** Observations that are genuinely present in this item. */
  relevant: string[];
  /**
   * Conclusions that are defensible from the content alone. "Definitely"
   * answers never appear here — that is the whole lesson.
   */
  acceptable: ConclusionId[];
  /** What was actually true, revealed after the child has committed. */
  truth: string;
  teaching: string;
}

export const EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: 'polished-animal',
    kind: 'image',
    title: 'A polished digital animal illustration',
    display: '🦌',
    label: 'A very smooth, glossy illustration of a deer with perfect fur detail',
    relevant: ['perfect', 'lighting', 'style'],
    acceptable: ['might-ai', 'not-enough'],
    truth: 'This one was generated by AI — but you could not have proved that by looking.',
    teaching:
      'You were right to be suspicious, and right not to say "definitely". Being correct by luck is not the same as having evidence.',
  },
  {
    id: 'child-robot',
    kind: 'image',
    title: 'A child’s hand-drawn robot',
    display: '🖍️',
    label: 'A wobbly crayon drawing of a robot with uneven arms',
    relevant: ['handmade', 'distorted'],
    acceptable: ['might-ai', 'not-enough'],
    truth: 'A nine-year-old drew this in felt tip.',
    teaching:
      '"Looks handmade" is a clue, not a proof — image tools can imitate crayon perfectly. Even here, the honest answer was "not enough evidence".',
  },
  {
    id: 'fantasy-text',
    kind: 'text',
    title: 'A short fantasy paragraph',
    display:
      'The bright dragon flew over the bright hills, and the hills were bright and wide and bright beneath the wide sky.',
    label: 'A paragraph that repeats the words bright and wide several times',
    relevant: ['repeats', 'style'],
    acceptable: ['might-ai', 'not-enough'],
    truth: 'Written by a person — a ten-year-old who liked the word "bright".',
    teaching:
      'Repetition is a famous "AI tell", and it is a weak one. Children repeat words. So do poets, on purpose.',
  },
  {
    id: 'edited-landscape',
    kind: 'image',
    title: 'A digitally edited landscape photo',
    display: '🏞️',
    label: 'A mountain photo with unusually vivid colours and a sky that does not match the light',
    relevant: ['lighting', 'edited', 'perfect'],
    acceptable: ['might-ai', 'not-enough'],
    truth: 'A real photograph, with the sky replaced using an AI tool.',
    teaching:
      'Both at once. A human took it and a machine changed it — which is why "human or AI" is often the wrong question.',
  },
  {
    id: 'cartoon',
    kind: 'image',
    title: 'A cartoon character',
    display: '🐰',
    label: 'A simple flat cartoon rabbit with clean outlines',
    relevant: ['perfect', 'style', 'none'],
    acceptable: ['not-enough', 'might-ai'],
    truth: 'Nobody involved in this activity knows. The file arrived with no history at all.',
    teaching:
      'Sometimes there genuinely is no answer available. Saying so is the most accurate thing an investigator can do.',
  },
  {
    id: 'voice-clip',
    kind: 'audio',
    title: 'A short voice clip',
    display: '🔊',
    label: 'A voice reading one sentence, with slightly even pacing and no breaths',
    relevant: ['voice', 'perfect', 'repeats'],
    acceptable: ['might-ai', 'not-enough'],
    truth: 'A synthetic voice — but a very good human voice actor sounds similar.',
    teaching:
      'Even pacing and no breathing are real clues. They still are not proof: some people read very evenly.',
  },
];

export const CREATION_CHOICES = [
  { id: 'draw', label: 'Draw a creature', emoji: '🎨' },
  { id: 'story', label: 'Write a four-sentence story', emoji: '✍️' },
  { id: 'character', label: 'Design a game character', emoji: '🎮' },
];

export const EVIDENCE_SCORING = {
  conclusion: 40,
  observation: 20,
  sourceCheck: 20,
  perRound: 100,
  total: EVIDENCE_ITEMS.length * 100,
  /** 70% of 600. */
  passMark: Math.round(EVIDENCE_ITEMS.length * 100 * 0.7),
} as const;

export const EVIDENCE_BADGE = 'evidence-investigator';

export function observationLabel(id: string): string {
  return OBSERVATIONS.find((o) => o.id === id)?.label.toLowerCase() ?? id;
}
